import Head from "next/head";
import styles from "../styles/Home.module.css";
import BattleMap from "../components/battleMap/BattleMap";
import { useResizeDetector } from "react-resize-detector";

export default function Home() {
  const { ref, width, height } = useResizeDetector();

  return (
    <div className={"container"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/src/public/favicon.ico" />
      </Head>

      <main>Hellow!</main>
    </div>
  );
}
