import Head from "next/head";
import { useResizeDetector } from "react-resize-detector";
import { signIn, useSession } from "next-auth/react";

export default function Home() {
  const { ref, width, height } = useResizeDetector();
  const session = useSession();

  console.log("Session ", session);
  return (
    <div className={"container"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/src/public/favicon.ico" />
      </Head>
      <main>
        Hellow!
        <>
          Not signed in <br />
          <button onClick={() => signIn()}>Sign in</button>
        </>
      </main>
    </div>
  );
}
