import Head from "next/head";

export default function Home(pageProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/src/public/favicon.ico" />
      </Head>
      <main>Hello my friend!</main>
    </>
  );
}
