import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import BaseMap from "../components/map/BaseMap";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div style={{width: "100vw", height: "99vh", overflow: "hidden"}}>
            <BaseMap />
        </div>
      </main>

    </div>
  )
}
