import { Campaign } from "features/campaign/Campaign";
import Head from "next/head";
import { useRouter } from "next/router";


export default function CampaignPage() {
  // TODO parse this id
  const { query: { id } } = useRouter();



  return (
    <div className={"container"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/src/public/favicon.ico" />
      </Head>

      <main>
        { id && <Campaign campaignId={String(id)} />}
      </main>
    </div>
  );
}
